version: '3.8'

services:
  # mysql:
  #   image: docker.io/bitnami/mysql:8.2
  #   ports:
  #     - '3306:3306'
  #   volumes:
  #     - 'mysql_data:/bitnami/mysql/data'
  #     - './MariaDB/migrations:/migrations'
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
  #   healthcheck:
  #     test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
  #     interval: 15s
  #     timeout: 5s
  #     retries: 6
  mysql:
    restart: always
    image: mariadb:10.9-jammy
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: firebnb
      MYSQL_USER: firebnb 
      MYSQL_PASSWORD: '123456'
    ports:
      - '3306:3306'
    volumes:
      - type: volume
        source: mysql_data
        target: /var/lib/mysql
        volume:
          nocopy: true
      - type: bind
        source: ./MariaDB/migrations
        target: /migrations
    
  mongodb:
    image: docker.io/bitnami/mongodb:7.0
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami/mongodb'

  laravel.test:
    build:
      context: ./Laravel/vendor/laravel/sail/runtimes/8.2
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: sail-8.2/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:80'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
      - './Laravel:/var/www/html'
    depends_on:
      - mysql
      - mongodb

volumes:
  mysql_data:
    driver: local
  mongodb_data:
    driver: local

networks:
  sail:
    driver: bridge